name: 🐛 Bug report
description: Describe a problem
labels: bug
title: '[Bug]'

body:
  - type: markdown
    attributes:
      value: |
        Some general tips:

        - Is this really a problem?
        - Is this a problem here?
        - Can this be solved in a different way?

  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        # - label: I agree to follow the [code of conduct](https://github.com/libi/dcron/blob/main/CODE_OF_CONDUCT.md)
        #   required: true
        - label: I searched [issues](https://github.com/libi/dcron/issues) and [discussions](https://github.com/libi/dcron/discussions) and couldn’t find anything (or linked relevant results below)
          required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected packages and versions
      description: Please test using the latest version of the relevant packages to make sure your issue has not already been fixed.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How did this happen? Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: OS
      description: What operating system are you using?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other (please specify in steps to reproduce)
    validations:
      required: false
