name: 🚀 Feature request
description: Suggest an idea
labels: enhancement
title: '[Feature]'

body:
  - type: markdown
    attributes:
      value: |
        Some general tips:

        - Is this really a problem?
        - Is this a problem here?

  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I agree to follow the [CONTRIBUTING](https://github.com/libi/dcron/blob/master/CONTRIBUTING.md)
          required: true
        - label: I searched [issues](https://github.com/libi/dcron/issues) and [discussions](https://github.com/libi/dcron/discussions) and couldn’t find anything (or linked relevant results below)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Please describe the problem you are trying to solve here.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What should happen? Please describe the desired behavior.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What are the alternative solutions? Can this be solved in a different way?
    validations:
      required: true
